# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FDRcontrol <- function(p, alpha) {
    .Call('fdrcontrol_FDRcontrol', PACKAGE = 'fdrcontrol', p, alpha)
}

